server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # json data를 snake_case로 전달하기 위해 설정
  jackson:
    property-naming-strategy: SNAKE_CASE

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/groupin?serverTimezone=Asia/Seoul
#    username: groupin
#    password: groupin1234

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/groupin
    username: root
    password: cos1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # Could not fetch the SequenceInformation from the database 에러 해결
    open-in-view: true
    hibernate:
      ddl-auto: create # update: 데이터 INSERT 후 서버 재실행해도 남아있음 / create: 서버 재실행시 INSERT된 데이터 사라짐 / none: 배포 후 사용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: sql_server

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: root
      password:

file:
  path: C:/workspace/springbootwork/upload/
  #path: /Users/jeongin/WORKSPACE/Spring/upload/


